server:
  port: 9000
spring:
  application:
    name: train12306-gateway${unique-name:}-service
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
